"""Templates for ``calflab new-plugin <type> <name>``.

Each template is a working plugin that passes its contract test unchanged, so
a new plugin starts green and shows up in the UI immediately.
"""

from __future__ import annotations

import re
from pathlib import Path

from calflab.plugins.types import PLUGIN_TYPES

_HEADER = '''"""{label}: a CALFLAB {ptype} plugin.

Generated by `calflab new-plugin {ptype} {name}`. Edit freely. The lab picks
up changes to this file automatically (hot reload). Parameters declared with
P(...) appear in the UI with sliders, units and tooltips; no UI code needed.
"""

from __future__ import annotations

'''

_BODIES: dict[str, str] = {
    "gene_definition": '''from calflab.model.genome import GeneDef, GenomeDefinition
from calflab.plugins import GeneDefinition, register


@register
class {cls}(GeneDefinition):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this genome."

    def definition(self) -> GenomeDefinition:
        return GenomeDefinition(
            name="{name}",
            version=1,
            description=self.description,
            genes=[
                GeneDef(id="body_length", default=400.0, min=200.0, max=600.0, unit="mm", group="Body",
                        description="Example gene."),
            ],
        )
''',
    "part_generator": '''from pydantic import BaseModel

from calflab.model.overrides import ElementParams, ParamValue
from calflab.model.spec import Body, Geom, RobotSpec
from calflab.plugins import BuildContext, PartGenerator, register
from calflab.schema import P


@register
class {cls}(PartGenerator):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe what this generator builds."
    genome_definition = "calf"  # the gene definition this generator reads

    class Params(BaseModel):
        scale: float = P(1.0, ge=0.5, le=2.0, step=0.05, desc="Uniform scale of the body.")

    def element_params(self, genes) -> ElementParams:
        # Stage 1: per-element parametric values, each naming its driving gene.
        return {{
            "trunk": {{
                "length": ParamValue(value=float(genes["trunk_length"]), unit="mm", gene="trunk_length"),
            }}
        }}

    def build(self, genes, params: ElementParams, ctx: BuildContext) -> RobotSpec:
        # Stage 2: explicit geometry from the (possibly overridden) parameters.
        length = params["trunk"]["length"].value * self.params.scale
        trunk = Body(id="trunk", name="Trunk", pos=(0.0, 0.0, 200.0))
        trunk.geoms.append(
            Geom(id="trunk.shell", shape="box", size=(length, 120.0, 120.0), mass_g=500.0)
        )
        return RobotSpec(name="{name}", bodies=[trunk])
''',
    "joint_type": '''from calflab.plugins import JointType, register


@register
class {cls}(JointType):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this joint type."
    dof = 1
    mjcf_type = "hinge"

    def mjcf_attrs(self, joint) -> dict[str, str]:
        return {{}}
''',
    "component": '''from calflab.components.library import Component, parse_component
from calflab.plugins import ComponentProvider, register


@register
class {cls}(ComponentProvider):
    """Prefer adding YAML to config/components/. Use a plugin for computed entries."""

    key = "{name}"
    label = "{label}"
    description = "TODO: describe these components."

    def components(self) -> list[Component]:
        return [
            parse_component({{
                "key": "{name}_example",
                "kind": "sensor",
                "type": "example",
                "name": "Example sensor",
                "mass_g": 1.0,
                "source": "TODO: datasheet URL",
                "verified": False,  # never set True in code
            }})
        ]
''',
    "controller": '''import numpy as np
from pydantic import BaseModel

from calflab import units as u
from calflab.plugins import ControlInfo, Controller, Observation, VectorDim, register
from calflab.schema import P


@register
class {cls}(Controller):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this controller."

    class Params(BaseModel):
        amplitude: float = P(5.0, unit="deg", ge=0, le=30, step=0.5, desc="Oscillation amplitude.")
        frequency: float = P(1.0, unit="Hz", ge=0.1, le=4, step=0.05, desc="Oscillation frequency.")

    @classmethod
    def vector_dims(cls) -> list[VectorDim]:
        # Parameters an optimizer may tune, with bounds in design units.
        return [VectorDim("amplitude", 0.0, 30.0), VectorDim("frequency", 0.3, 3.0)]

    def reset(self, info: ControlInfo, seed: int = 0) -> None:
        self.info = info

    def act(self, obs: Observation) -> np.ndarray:
        # Return one target joint angle (rad) per actuator.
        a = u.deg_to_rad(self.params.amplitude)
        return self.info.rest + a * np.sin(2 * np.pi * self.params.frequency * obs.t)
''',
    "behavior": '''from typing import Any

from pydantic import BaseModel

from calflab.plugins import Behavior, register
from calflab.schema import P


@register
class {cls}(Behavior):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this behavior."

    class Params(BaseModel):
        intensity: float = P(0.5, ge=0, le=1, step=0.05, desc="How strongly the behavior is expressed.")

    def tick(self, t: float, sensors: dict[str, Any]) -> dict[str, Any]:
        return {{"gait": "trot", "intensity": self.params.intensity}}
''',
    "fitness_term": '''from typing import Any

from pydantic import BaseModel

from calflab.plugins import FitnessTerm, register
from calflab.schema import P


@register
class {cls}(FitnessTerm):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe what this term rewards."

    class Params(BaseModel):
        target: float = P(0.3, unit="m/s", ge=0, le=2, step=0.05, desc="Speed that earns the full score.")

    def evaluate(self, metrics: dict[str, Any], context: dict[str, Any]) -> float:
        # Higher is better. `metrics` keys are listed in calflab.sim.metrics.METRIC_DEFS.
        return min(1.0, float(metrics.get("speed_mps", 0.0)) / self.params.target)
''',
    "behavior_descriptor": '''from typing import Any

from calflab.plugins import BehaviorDescriptor, register


@register
class {cls}(BehaviorDescriptor):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this archive axis."
    range = (0.0, 1.0)
    unit = ""

    def describe_candidate(self, spec, metrics: dict[str, Any], controller_params: dict[str, Any]) -> float:
        return float(metrics.get("stability", 0.0))
''',
    "optimizer": '''from pydantic import BaseModel

from calflab.plugins import Optimizer, register
from calflab.schema import P


@register
class {cls}(Optimizer):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this optimizer."
    stub = True  # remove once run() is implemented

    class Params(BaseModel):
        generations: int = P(10, ge=1, le=1000, desc="Number of generations.")

    def run(self, problem, backend, report):
        # See calflab.evolve.map_elites for a complete example.
        raise NotImplementedError("TODO: implement {name}.run()")
''',
    "simulator": '''from calflab.plugins import Simulator, register


@register
class {cls}(Simulator):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this simulator."
    stub = True  # remove once rollout() is implemented

    def rollout(self, spec, controller, settings, **kwargs):
        # See calflab.builtin.simulators for the MuJoCo implementation.
        raise NotImplementedError("TODO: implement {name}.rollout()")
''',
    "compute_backend": '''from calflab.plugins import ComputeBackend, Task, register


@register
class {cls}(ComputeBackend):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe where tasks run."

    def available(self) -> tuple[bool, str]:
        return True, "runs in-process"

    def map(self, tasks: list[Task], on_result=None, cancelled=None) -> list:
        from calflab.compute.worker import run_task

        results = []
        for i, task in enumerate(tasks):
            if cancelled and cancelled():
                break
            r = run_task(task.fn, task.payload)
            results.append(r)
            if on_result:
                on_result(i, r)
        return results
''',
    "exporter": '''from pathlib import Path

from pydantic import BaseModel

from calflab.plugins import ExportContext, Exporter, register
from calflab.schema import P


@register
class {cls}(Exporter):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe what this exporter writes."
    formats = ["txt"]
    category = "geometry"

    class Params(BaseModel):
        include_ids: bool = P(True, desc="List element IDs in the output.")

    def export(self, ctx: ExportContext, out_dir: Path) -> list[Path]:
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"{{ctx.design_name}}_{name}.txt"
        lines = [f"{{ctx.spec.name}}: {{len(ctx.spec.bodies)}} bodies, {{ctx.spec.total_mass_g():.0f}} g"]
        if self.params.include_ids:
            lines += [b.id for b in ctx.spec.bodies]
        path.write_text("\\n".join(lines), encoding="utf-8")
        return [path]
''',
    "analysis": '''from typing import Any

from pydantic import BaseModel

from calflab.plugins import Analysis, register
from calflab.schema import P


@register
class {cls}(Analysis):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this analysis."

    class Params(BaseModel):
        threshold: float = P(0.5, ge=0, le=1, step=0.05, desc="Example threshold.")

    def run(self, lab: Any) -> dict[str, Any]:
        spec = lab.design().spec
        return {{"bodies": len(spec.bodies), "mass_g": spec.total_mass_g()}}
''',
    "panel": '''from calflab.plugins import Panel, register


@register
class {cls}(Panel):
    """A panel declared as data; the web app renders it generically."""

    key = "{name}"
    label = "{label}"
    description = "TODO: describe this panel."
    workspace = None  # or a workspace id such as "form" to add it there by default
    widgets = [
        {{"kind": "markdown", "text": "## {label}\\nEdit `plugins/{name}.py` to change this panel."}},
        {{"kind": "analysis", "analysis": "mass_budget"}},
    ]
''',
    "command": '''from typing import Any

from pydantic import BaseModel

from calflab.plugins import Command, register
from calflab.schema import P


@register
class {cls}(Command):
    key = "{name}"
    label = "{label}"
    description = "TODO: describe this command."
    category = "Custom"
    mutates = False  # True = edits the document (logged, undoable)

    class Params(BaseModel):
        message: str = P("hello", desc="Text to return.")

    def run(self, lab: Any, state: Any) -> Any:
        return {{"message": self.params.message}}
''',
}

_TEST = '''"""Contract test for the {ptype} plugin `{name}` (generated)."""

from calflab.plugins import load_plugins, registry
from calflab.plugins.contracts import check_plugin


def test_{name}_contract():
    load_plugins()
    cls = registry.get("{ptype}", "{name}")
    assert check_plugin(cls) == []
'''

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def class_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def render(ptype: str, name: str) -> tuple[str, str]:
    """Return (plugin source, test source)."""
    if ptype not in PLUGIN_TYPES:
        raise ValueError(f"Unknown plugin type {ptype!r}. Choose one of: {', '.join(PLUGIN_TYPES)}")
    if not _NAME_RE.match(name):
        raise ValueError(f"Plugin name {name!r} must be snake_case (letters, digits, underscores)")
    label = name.replace("_", " ").capitalize()
    fmt = {"name": name, "cls": class_name(name), "label": label, "ptype": ptype}
    source = _HEADER.format(**fmt) + _BODIES[ptype].format(**fmt)
    return source, _TEST.format(**fmt)


def create(ptype: str, name: str, plugins_dir: Path, tests_dir: Path, force: bool = False) -> tuple[Path, Path]:
    """Write the plugin and its contract test. Refuses to overwrite unless ``force``."""
    source, test = render(ptype, name)
    plugin_path = plugins_dir / f"{name}.py"
    test_path = tests_dir / f"test_{name}.py"
    for p in (plugin_path, test_path):
        if p.exists() and not force:
            raise FileExistsError(f"{p} already exists (use --force to overwrite)")
    plugins_dir.mkdir(parents=True, exist_ok=True)
    tests_dir.mkdir(parents=True, exist_ok=True)
    plugin_path.write_text(source, encoding="utf-8")
    test_path.write_text(test, encoding="utf-8")
    return plugin_path, test_path
